### ISSUE TITLE
Feedback for “Affiliate Wallet”

### ISSUE THREAD

**Issue by cakemooner** [Azuro-protocol/gem-docs#129]
Simply using own affiliate wallet seems not going to get rewarded as stated in docs. pubBet function in BetExpress contract does not consume the affiliate address. LP contract only carries one affiliate address. And in your sdk config.js always hardcode proxyFront to bookmaker.xyz address. How are you going to know what affiliates contributed in a month except for bookmaker.xyz?

BTW, I am trying to join Discord I got banned for no reason. Please unban me!

**Comment by on47sky** [comment]
Hello @cakemooner!
- All bets are made on LP contracts only. BetExpress is a Core contract, and its address is provided as a parameter for combo bets.
- ProxyFront is not linked to any affiliate. Any frontend app can utilize a single ProxyFront contract. It serves as a helper contract enabling batch placement and redemption of bets.
- The affiliate address is not hardcoded in the SDK. It's included as a parameter in the bet data. Regardless of which contract or wallet is used to place a bet, the affiliate address can be specified. Refer to the [documentation](https://gem.azuro.org/hub/apps/sdk/write-hooks/usePrepareBet#usage) for more details. 

You can validate it:
1. Place a bet with your own affiliate address.
2. [Query bets from the public subgraph](https://thegraph.azuro.org/subgraphs/name/azuro-protocol/azuro-api-polygon-v3/graphql?query=query+Bets+%7B%0A++bets%28where%3A+%7B+affiliate_contains_nocase%3A+%220x...%22+%7D%29+%7B%0A++++betId%0A++++actor%0A++%7D%0A%7D) (simply replace `"0x..."` with your affiliate address).
