### ISSUE TITLE
Multilingual support on Azuro-Protocol wensite 

### ISSUE THREAD

**Issue by anuragasawa20** [Azuro-protocol/gem-docs#38]
website is only support English language which limit down the users. users from non-english Native Languages can't feel comfortable. 
We should add multiple other Languages. This will improve the user experience and ensure that the documentation is clear and reached a wider developer audience.
Proposed Solution
Apply the translate library to the docs so it can be translated in multiple other languages. It can be done by i18n. I have been done it for push protocol (https://push.org/) and got bounty. I will do this thing in just 3-4 Days.

**Comment by vaivanov** [comment]
Hello, multilingual support for GEM is not in our roadmap now, thanks
