### ISSUE TITLE
Feedback for “Place a Bet”

### ISSUE THREAD

**Issue by CodeCraftsCanvas** [Azuro-protocol/gem-docs#79]
doesnt work anymore

**Comment by on47sky** [comment]
Hello @CodeCraftsCanvas!
Could you kindly delve a bit deeper into the exact issue you're encountering? Can you share the specific part you have tried to implement from this doc (ethers/wagmi, single/combo/batch)? Also, please provide any error message received. Your additional information will greatly assist us in providing a more accurate response.
